### PR TITLE
Stop allowing voting on closed cycle

### LINKED ISSUE #90: Remove the possibility to vote on forum question of a closed cycle
### Overview 

Currently it is possible to insert votes for closed cycles. This should not be possible.

### PR DESCRIPTION
**Pull request by diegoalzate**
closes #90 

# overview
- adds unit tests for saving votes
- separates saveVote function from inserting the vote to the db
- only allows voting if cycle is in status: "OPEN"

### CODE REVIEW

**Review by camilovegag — APPROVED** [review]
Changes working as expected, now a new front end issue to handle errors is indeed needed!

**Comment by camilovegag** [comment]
> Changes working as expected, now a new front end issue to handle errors is indeed needed!

Created an issue [here](https://github.com/lexicongovernance/forum-frontend/issues/80)

**Review by MartinBenediktBusch — CHANGES_REQUESTED** [review]
The test suit just does not pass even after restarting the proccess multiple times. There are two types of errors that occur in the registration.spec.ts file and in the votes.spec.ts file. 

 1: ```PostgresError: duplicate key value violates unique constraint 
 "pg_namespace_nspname_index"```
2: ``` PostgresError: insert or update on table "votes" violates foreign key constraint "votes_user_id_users_id_fk"```

Furthermore, I think an interaction is created that makes the test fail even localy sometimes. 

Could it be due to the order of deleting data in the seed database? For example, federated  credentials should be deleted last as it is the highest level:

```
async function cleanup(dbPool: PostgresJsDatabase<typeof db>) {
  await dbPool.delete(db.federatedCredentials);
  await dbPool.delete(db.votes);
  await dbPool.delete(db.registrationData);
  await dbPool.delete(db.registrationFields);
  await dbPool.delete(db.registrations);
  await dbPool.delete(db.usersToGroups);
  await dbPool.delete(db.users);
  await dbPool.delete(db.groups);
  await dbPool.delete(db.questionOptions);
  await dbPool.delete(db.forumQuestions);
  await dbPool.delete(db.cycles);
  await dbPool.delete(db.events);
}

```

**Comment by diegoalzate** [comment]
@MartinBenediktBusch I think you are right, i was thinking about separating db migrations from the tests and that can also help. i will circle back to this during the day

**Pull request merged**
